server:
  port: 10493
spring:
  datasource:
    url: jdbc:mysql://${dbaddr:localhost}:${dbport:3306}/${dbname:GuardianCheck2}?useSSL=${useSSL:false}
    username: ${dbuser:root}
    password: ${dbpass}
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update