gcheck:
  defaultEmailDomain: "@avonoldfarms.com"
server:
  port: 10493
spring:
  datasource:
    url: jdbc:mysql://${dbaddr:localhost}:${dbport:3306}/${dbname:GuardianCheck2}?useUnicode=yes&characterEncoding=UTF-8&useSSL=${useSSL:false}
    username: ${dbuser:root}
    password: ${dbpass}
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    from: "AOF Activity Sign-up<signups@233.com.hk>"
    host: hn2.guardiantech.com.cn
    protocol: smtps
    port: 587
    username: ${smtpusr:signups@233.com.hk}
    password: ${smtppass}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.transport.protocol: smtps